# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# ***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.
# SIMPLY APPEND THE REQUIRED VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
# ***********************************************************************

#*************************************************************************************************************************
# groups
#*************************************************************************************************************************
# functional_groups_config.yml file takes input parameters for the composable functional groups.
# This file contains functional groups details used by the omnia for cluster formation.
# groups: - Groups will contain the list of groups defined by the user. User must define atleast one group.
#   grpN:                   - <Mandatory> "grpN" -  User defined name of the group. Range for N is 0-99
#     cluster_name:         - <Conditional Mandatory> Name of the cluster to which the group belongs. This input is case-sensitive. This will remain empty for groups which are not associated with any kubernetes roles.
#     location_id:          - <Mandatory> SU-<n>.RACK-<n> Scalable unit and rack number range is 0-99. This input is case-sensitive. Please use uppercase letters only.
#     parent_service_node:  - <Conditional Mandatory> service tag of associated service node.
#                           - This field will be empty for group of nodes which is associated with ‘login_node’, ‘compiler_node’,
#                               ‘service_kube_control_plane’, 'service_etcd', 'service_kube_node', ‘kube_control_plane’, ‘etcd’, 'slurm_control_node’.
#                               If ‘service_kube_control_plane’, 'service_etcd', 'service_kube_node' roles are not defined, then value will be empty.
#     additional_pkg_profile - <Optional> If any additional packages need to install on nodes associtted with define group

groups:
  grp0:
    location_id: SU-1.RACK-1
    cluster_name: ""
    parent_service_node: ""
    additional_pkg_profile:
#      - { name: "cuda_x84_64", version: "12.9.1"}
#      - { name: "ofed_x84_64", version: "24.10-3.2.5.0"}
#      - { name: "openldap_x84_64"}

  # grp1:
  #   location_id: SU-1.RACK-2
  #   cluster_name: ""
  #   parent_service_node: ""
  #    additional_pkg_profile:
  #      - { name: "cuda_x84_64", version: "12.9.1"}
  #      - { name: "ofed_x84_64", version: "24.10-3.2.5.0"}
  #      - { name: "openldap_x84_64"}

#************************************************************************************************************************
#  functional_groups
#************************************************************************************************************************
# Atleast one functional groups is mandatory, and functional groups names are pre-defined.
# Maximum number of functional groups supported are 100.
# Note: Nested functional groups are not supported.
# The functional group names are case sensitive
#   - name:                           - <Mandatory> Name of the role, can be any of the following Omnia defined roles.
#     groups:                         - <Mandatory> list of groups defined by the user
#

# This table lists the functional groups and the layers they belong to in the cluster.

# +-----------------------------------+-----------------+     +------------------------+----------------+
# | Functional Group Name             | Layer           |     | Functional Group Name  | Layer          |
# +-----------------------------------+-----------------+     +------------------------+----------------+
# | service_kube_control_plane_x86_64 | management      |     | default_x86_64         | compute        |
# | service_etcd_x86_64               | management      |     | kube_node_x86_64       | compute        |
# | service_kube_node_x86_64          | management      |     | slurm_node_x86_64      | compute        |
# | login_node_x86_64                 | management      |     | default_aarch64        | compute        |
# | compiler_node_x86_64              | management      |     | kube_node_aarch64      | compute        |
# | kube_control_plane_x86_64         | management      |     | slurm_node_aarch64     | compute        |
# | etcd_x86_64                       | management      |     |                        |                |
# | slurm_control_node_x86_64         | management      |     |                        |                |
# | login_node_aarch64                | management      |     |                        |                |
# | compiler_node_aarch64             | management      |     |                        |                |
# +-----------------------------------+-----------------+     +------------------------+----------------+

# Default Functional Group of architecture x86_64:
# --------------------------
#
# This functional group is provided to cover the default compute nodes of the cluster.
#
# If user wants to provision the group of nodes without installing any
# additional package other than drivers and kernel parameters then this funcitonal group can be used.
#
# This functional group belongs to the compute layer.
#
Roles:
  - name: "default_x86_64"
    groups:
      - grp0



# Service k8s head Role: Service Cluster Kubernetes master node for groups to add into service_kube_control_plane role can be provided in this role
# ----------------------------------------------------------------------------------------------------
#
# This role is used to configure kubernetes master on service cluster.
#
# This role should not have same group as of K8s head Role.
#
# The nodes included in this role will have the necessary tools and
# configurations to configure kubernetes master on service cluster.
#
# The nodes in this role can be used to run kubernetes master on service cluster.
#
# Service k8s head Role: Service Cluster Kubernetes master node for groups to add into service_kube_control_plane role can be provided in this role
  # - name: "service_kube_control_plane"
  #   groups:
  #     - grp0
  #     - grp1

#
# Service etcd Role: Service Cluster Kubernetes etcd node groups to add into service cluster k8s role can be provided in this role
# ------------------------------------------------------------------------------------
#
# This role is used to configure the nodes for Kubernetes etcd on service cluster.
#
# This role should not have same group as of K8s etcd Role.
#
# The nodes included in this role will have the necessary tools and
# configurations to configure Kubernetes etcd on service cluster.
#
# The nodes in this role can be used to run Kubernetes etcd on service cluster.
#
# Service etcd Role: Service Cluster Kubernetes etcd node groups to add into service cluster k8s role can be provided in this role
  # - name: "service_etcd"
  #   groups:
  #     - grp0
  #     - grp1

#
# Service k8s Worker Role: Service Cluster Kubernetes worker node groups to add into service cluster k8s role can be provided in this role
# ------------------------------------------------------------------------------------
#
# This role is used to configure the nodes for Kubernetes worker on service cluster.
#
# This role should not have same group as of K8s Worker node.
#
# The nodes included in this role will have the necessary tools and
# configurations to configure Kubernetes worker on service cluster.
#
# The nodes in this role can be used to run Kubernetes worker on service cluster.
#
# Service k8s Worker Role: Service Cluster Kubernetes worker node groups to add into service cluster k8s role can be provided in this role
  # - name: "service_kube_node"
  #   groups:
  #     - grp0
  #     - grp1

# ----------------------------------------Not Supported ( Future Use )---------------------------------
# Service Node Role: Service node groups to add into service_node role can be provided in this role
# ------------------------------------------------------------------------------------
#
# This role is used to configure the nodes for service group. It belongs to the management layer.
#
# The nodes included in this role will have the necessary tools and
# configurations to configure service node.
#
# The nodes in this role can be used to run service.
#
  # - name: "service_node"
  #   groups:
  #     - grp0
  #     - grp1

#
# K8s head Role: Kubernetes master node groups to add into kube_control_plane role can be provided in this role
# ---------------------------------------------------------------------------------------
#
# This role is used to configure the nodes for Kubernetes master. It belongs to the management layer.
#
# The nodes included in this role will have the necessary tools and
# configurations to run Kubernetes master.
#
# The nodes in this role can be used to run Kubernetes master.
#
# K8s head Role: Kubernetes master groups to add into etcd role can be provided in this role
  # - name: "kube_control_plane"
  #   groups:
  #     - grp0
  #     - grp1

#
# K8s etcd Role: Kubernetes etcd node groups to add into k8s role can be provided in this role
# ---------------------------------------------------------------------------------------------
#
# This role is used to configure the nodes for Kubernetes etcd. It belongs to the management layer.
#
# The nodes included in this role will have the necessary tools and
# configurations to run Kubernetes etcd.
#
# The nodes in this role can be used to run Kubernetes etcd.
#
# K8s etcd Role: Kubernetes etcd groups to add into k8s etcd role can be provided in this role
  # - name: "etcd"
  #   groups:
  #     - grp0
  #     - grp1

#
# K8s Worker Role: Kubernetes worker node groups to add into k8s role can be provided in this role
# -----------------------------------------------------------------------------------------------
#
# This role is used to configure the nodes for Kubernetes worker. It belongs to the compute layer.
#
# The nodes included in this role will have the necessary tools and
# configurations to run Kubernetes worker.
#
# The nodes in this role can be used to run Kubernetes worker.
#
# K8s Worker Role: Kubernetes worker groups to add into k8s worker role can be provided in this role
  # - name: "kube_node"
  #   groups:
  #     - grp0
  #     - grp1

#
# Slurm Head Role: Slurm head node groups to add into Slurm role can be provided in this role
# ------------------------------------------------------------------------------------------
#
# This role is used to configure the nodes for Slurm head. It belongs to the management layer.
#
# The nodes included in this role will have the necessary tools and
# configurations to run Slurm head.
#
# The nodes in this role can be used to run Slurm head.
# This role belongs to the compute layer.
#
# Slurm Head Role: Slurm head groups to add into slurm_control_node role can be provided in this role
  # - name: "slurm_control_node"
  #   groups:
  #     - grp0
  #     - grp1

#
# Slurm Worker Role: Slurm worker node groups to add into Slurm role can be provided in this role
# ------------------------------------------------------------------------------------------------
#
# This role is used to configure the nodes for Slurm worker. It belongs to the compute layer.
#
# The nodes included in this role will have the necessary tools and
# configurations to run Slurm worker.
#
# The nodes in this role can be used to run Slurm worker.
#
# Slurm Worker Role: Slurm worker groups to add into Slurm role can be provided in this role
  # - name: "slurm_node"
  #   groups:
  #     - grp0
  #     - grp1

#
# Login Node Role:
# -----------
#
# This role is used to configure the nodes for user logins. It belongs to the management layer.
#
# The nodes included in this role will have the necessary tools and configurations
# to support user login activities.
#
# The user is not allowed to change the name of this role.
#
  # - name: "login_node"
  #   groups:
  #     - grp0
  #     - grp1

#
# Auth Server Role:
# -----------------
#
# This role is used to configure the nodes for authentication. It belongs to the management layer.
#
# The nodes included in this role will have the necessary tools and configurations
# to support authentication activities.
#
# The user is not allowed to change the name of this role.
#
  # - name: "auth_server"
  #   groups:
  #     - grp0
  #     - grp1

#
# Compiler Node Role:
# --------------
#
# This role is used to configure the nodes for compilation. It belongs to the management layer.
#
# The nodes included in this role will have the necessary tools and
# configurations to perform compilation.
#
# The nodes in this role can be used to compile the code.
#
# Compiler Node Role: Compiler groups to add into compiler_node role can be provided in this role
  # - name: "compiler_node"
  #   groups:
  #     - grp0
  #     - grp1
