---
galaxy_info:
  role_name: pxe_buildstream_manager
  namespace: omnia
  author: Dell Technologies Omnia Team
  description: Manage PXE boot operations with BuildStream integration
  company: Dell Technologies

  license: Apache-2.0

  min_ansible_version: "2.20"

  platforms:
    - name: EL
      versions:
        - "10"

  galaxy_tags:
    - hpc
    - buildstream
    - provisioning
    - gitlab

dependencies: []
