# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Overridable defaults
input_project_dir: "/opt/omnia/input"
oim_shared_path: "/opt/omnia"
oim_data_path: "/opt/omnia/.data"
oim_provision_path: "/opt/omnia/provision"
tmp_path: "/tmp"
cluster_os_version: "10.0"
admin_nic_ip: "{{ hostvars['localhost']['admin_nic_ip'] | default('127.0.0.1') }}"
admin_nic_cidr: "{{ hostvars['localhost']['admin_nic_cidr'] | default('10.0.0.0/24') }}"

# MinIO S3 for boot images
minio_ip: "{{ hostvars['localhost']['minio_ip'] | default(admin_nic_ip) }}"
minio_port: "9000"
minio_bucket: "omnia"

# Worker drain options
worker_drain_delete_emptydir: true
