# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Set sample file paths
  ansible.builtin.set_fact:
    _gitlab_example_repo_path: "catalog/{{ catalog_file_relative_path }}"
    _gitlab_example_hosted_path: >-
      {{ gitlab_hosted_payload_dir }}/catalog/
      {{- catalog_file_relative_path }}
    _gitlab_example_encoded_path: >-
      {{ ('catalog/' ~ catalog_file_relative_path)
         | urlencode
         | replace('/', '%2F') }}

- name: Check if catalog exists in repository
  ansible.builtin.uri:
    url: >-
      {{ gitlab_external_url_computed }}/api/v4/projects/
      {{- gitlab_project_id }}/repository/files/
      {{- _gitlab_example_encoded_path }}?ref={{ gitlab_default_branch }}
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ gitlab_root_token }}"
    status_code: [200, 404]
    validate_certs: false
  register: gitlab_example_catalog_check
  no_log: true

- name: Ensure sample parent directory exists on GitLab host
  ansible.builtin.file:
    path: "{{ _gitlab_example_hosted_path | dirname }}"
    state: directory
    mode: '0755'

- name: Copy sample file to GitLab host
  ansible.builtin.copy:
    src: "{{ catalog_file_path }}"
    dest: "{{ _gitlab_example_hosted_path }}"
    mode: '0644'

- name: Read sample file from GitLab host
  ansible.builtin.slurp:
    src: "{{ _gitlab_example_hosted_path }}"
  register: gitlab_example_catalog_content

- name: Create sample file in GitLab repository
  when: gitlab_example_catalog_check.status == 404
  ansible.builtin.uri:
    url: >-
      {{ gitlab_external_url_computed }}/api/v4/projects/
      {{- gitlab_project_id }}/repository/files/
      {{- _gitlab_example_encoded_path }}
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_root_token }}"
    body_format: json
    body:
      branch: "{{ gitlab_default_branch }}"
      encoding: base64
      content: "{{ gitlab_example_catalog_content.content }}"
      commit_message: "Add sample: {{ catalog_file_relative_path }}"
    status_code: [200, 201]
    validate_certs: false
  no_log: true

- name: Update sample file in GitLab repository
  when:
    - gitlab_example_catalog_check.status == 200
    - >-
      (gitlab_example_catalog_check.json.content | b64decode) !=
      (gitlab_example_catalog_content.content | b64decode)
  ansible.builtin.uri:
    url: >-
      {{ gitlab_external_url_computed }}/api/v4/projects/
      {{- gitlab_project_id }}/repository/files/
      {{- _gitlab_example_encoded_path }}
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ gitlab_root_token }}"
    body_format: json
    body:
      branch: "{{ gitlab_default_branch }}"
      encoding: base64
      content: "{{ gitlab_example_catalog_content.content }}"
      commit_message: "Update sample: {{ catalog_file_relative_path }}"
    status_code: [200, 201]
    validate_certs: false
  no_log: true
