---
galaxy_info:
  role_name: validate_install_os_config
  namespace: omnia
  author: Dell Technologies Omnia Team
  description: Validates install_os_config.yml parameters for the OS installation utility
  company: Dell Technologies

  license: Apache-2.0

  min_ansible_version: "2.20"

  platforms:
    - name: EL
      versions:
        - "10"

  galaxy_tags:
    - hpc
    - dell
    - validation
    - osinstall

dependencies: []
