#!/bin/bash

docker_command=$1
if [ $docker_command = "start" ]; then
    docker_ps_result=$(docker ps -a | grep "registry")
    if [ -z $docker_ps_result ]; then
        docker run -d -p 5001:5000 --restart=always --name registry \
          -v `pwd`/data:/data \
          -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data \
          -v `pwd`/certs:/certs \
          -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
          -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
          registry:2
    else
        docker start registry
    fi
elif [ $docker_command = "stop" ]; then
    docker stop registry
else
    echo "The parameter is wrong."
fi