---
galaxy_info:
  role_name: ome_discovery
  namespace: omnia
  description: "Omnia discovery role: ome_discovery"
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
dependencies: []
