#  Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# project_name is defined in vars/default.yml as "project_default"
# No need to read from separate project_default.yml file

- name: Set input_project_dir
  ansible.builtin.set_fact:
    input_project_dir: "{{ repo_manager_input_project_dir | default(repo_manager_input_dir + '/' + (project_name | default(project_default))) }}"
    project_name: "{{ project_name | default(project_default) }}"
    cacheable: true
  tags: always

- name: Verify the project directory exists
  ansible.builtin.stat:
    path: "{{ input_project_dir }}"
  register: verify_project_dir
  tags: always

- name: Fail if project directory does not exist
  ansible.builtin.fail:
    msg: "{{ project_dir_not_exist_fail_msg }}"
  when: not verify_project_dir.stat.exists
  tags: always


- name: Include repo_manager metadata vars
  ansible.builtin.include_vars:
    file: "{{ repo_manager_metadata_file_path }}"
    name: oim_shared_path_from_metadata
  when: repo_manager_metadata_support | default(false)
  tags: always
