# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Discovery Module - BMC PXE Mapping Functions.

Functions for verifying BMC PXE mapping files generated by discovery playbook.
"""

import re
from typing import Dict, Any, List

import yaml

from automation_library.core import run_in_container, load_input_file
from ..vars import (
    BMC_PXE_MAPPING_PATH,
    BMC_PXE_MAPPING_PREFIX,
    SUPPORTED_COLUMNS,
    SUPPORTED_FUNCTIONAL_GROUPS,
    GROUPS_REQUIRING_PARENT_SERVICE_TAG,
    VALID_PARENT_FUNCTIONAL_GROUPS,
    NETWORK_SPEC_FILE,
)


def get_latest_bmc_pxe_mapping_file(host) -> Dict[str, Any]:
    """
    Get the latest BMC PXE mapping file (by timestamp).

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, filename, filepath, timestamp, error
    """
    result = {
        "success": False,
        "filename": "",
        "filepath": "",
        "timestamp": "",
        "error": "",
    }

    cmd = run_in_container(
        host,
        f"bash -c 'ls -1 {BMC_PXE_MAPPING_PATH}/{BMC_PXE_MAPPING_PREFIX}*.csv 2>/dev/null | sort -r | head -1'"
    )

    if cmd.rc != 0 or not cmd.stdout.strip():
        result["error"] = f"No BMC PXE mapping files found matching {BMC_PXE_MAPPING_PREFIX}*.csv"
        return result

    filepath = cmd.stdout.strip()
    filename = filepath.split("/")[-1]

    match = re.search(r"bmc_pxe_mapping_file_(\d{8}T\d{6})\.csv", filename)
    result["timestamp"] = match.group(1) if match else "unknown"
    result["filename"] = filename
    result["filepath"] = filepath
    result["success"] = True
    return result


def read_bmc_pxe_mapping_raw(host, filepath: str = None) -> Dict[str, Any]:
    """
    Read BMC PXE mapping file and return raw headers and rows.

    Args:
        host: Testinfra host object
        filepath: Optional path to specific file

    Returns:
        Dict with success, headers, rows, error
    """
    result = {
        "success": False,
        "headers": [],
        "rows": [],
        "error": "",
    }

    if not filepath:
        latest = get_latest_bmc_pxe_mapping_file(host)
        if not latest["success"]:
            result["error"] = latest["error"]
            return result
        filepath = latest["filepath"]

    cmd = run_in_container(host, f"cat '{filepath}'")
    if cmd.rc != 0:
        result["error"] = f"Failed to read {filepath}: {cmd.stderr}"
        return result

    lines = cmd.stdout.strip().split("\n")
    if not lines:
        result["error"] = "PXE mapping file is empty"
        return result

    result["headers"] = [h.strip() for h in lines[0].split(",")]

    for line in lines[1:]:
        if line.strip():
            result["rows"].append([v.strip() for v in line.split(",")])

    result["success"] = True
    return result


def get_network_spec_subnets(host) -> Dict[str, Any]:
    """
    Get admin and IB subnets from network_spec.yml.

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, admin_subnet, ib_subnet, error
    """
    result = {
        "success": False,
        "admin_subnet": "",
        "ib_subnet": "",
        "error": "",
    }

    config = load_input_file(host, NETWORK_SPEC_FILE)
    if not config:
        result["error"] = "network_spec.yml not found or empty"
        return result

    networks = config.get("Networks", [])
    for net in networks:
        if "admin_network" in net:
            result["admin_subnet"] = net["admin_network"].get("subnet", "")
        if "ib_network" in net:
            result["ib_subnet"] = net["ib_network"].get("subnet", "")

    result["success"] = True
    return result


def verify_pxe_mapping_columns(host) -> Dict[str, Any]:
    """
    Verify BMC PXE mapping file has all required columns.

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, present_columns, missing_columns, extra_columns, details, error
    """
    result = {
        "success": False,
        "present_columns": [],
        "missing_columns": [],
        "extra_columns": [],
        "details": "",
        "error": "",
    }

    mapping = read_bmc_pxe_mapping_raw(host)
    if not mapping["success"]:
        result["error"] = mapping["error"]
        return result

    file_headers = set(mapping["headers"])
    required_headers = set(SUPPORTED_COLUMNS)

    result["present_columns"] = sorted(list(file_headers & required_headers))
    result["missing_columns"] = sorted(list(required_headers - file_headers))
    result["extra_columns"] = sorted(list(file_headers - required_headers))

    if result["missing_columns"]:
        result["details"] = f"Missing columns: {', '.join(result['missing_columns'])}"
        result["error"] = result["details"]
    else:
        result["success"] = True
        result["details"] = f"All {len(SUPPORTED_COLUMNS)} required columns present"

    return result


def verify_functional_groups_supported(host) -> Dict[str, Any]:
    """
    Verify all functional groups in PXE mapping are Omnia-supported.

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, supported_groups, unsupported_groups, details, error
    """
    result = {
        "success": False,
        "supported_groups": [],
        "unsupported_groups": [],
        "details": "",
        "error": "",
    }

    mapping = read_bmc_pxe_mapping_raw(host)
    if not mapping["success"]:
        result["error"] = mapping["error"]
        return result

    try:
        fg_idx = mapping["headers"].index("FUNCTIONAL_GROUP_NAME")
    except ValueError:
        result["error"] = "FUNCTIONAL_GROUP_NAME column not found"
        return result

    found_groups = set()
    for row in mapping["rows"]:
        if len(row) > fg_idx and row[fg_idx]:
            found_groups.add(row[fg_idx])

    supported_set = set(SUPPORTED_FUNCTIONAL_GROUPS)
    result["supported_groups"] = sorted(list(found_groups & supported_set))
    result["unsupported_groups"] = sorted(list(found_groups - supported_set))

    if result["unsupported_groups"]:
        result["details"] = f"Unsupported functional groups: {', '.join(result['unsupported_groups'])}"
        result["error"] = result["details"]
    else:
        result["success"] = True
        result["details"] = f"All {len(result['supported_groups'])} functional groups are supported"

    return result


def verify_ip_correlation(host) -> Dict[str, Any]:
    """
    Verify ADMIN_IP and IB_IP correlation with BMC_IP based on network_spec.yml.

    IP correlation logic from discovery:
    - ADMIN_IP = admin_subnet[0:2] + bmc_ip[2:4]
    - IB_IP = ib_subnet[0:2] + bmc_ip[2:4]

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, valid_count, invalid_rows, details, error
    """
    result = {
        "success": False,
        "valid_count": 0,
        "invalid_rows": [],
        "details": "",
        "error": "",
    }

    # Get subnets from network_spec.yml
    subnets = get_network_spec_subnets(host)
    if not subnets["success"]:
        result["error"] = subnets["error"]
        return result

    admin_subnet = subnets["admin_subnet"]
    ib_subnet = subnets["ib_subnet"]

    if not admin_subnet:
        result["error"] = "admin_subnet not found in network_spec.yml"
        return result

    mapping = read_bmc_pxe_mapping_raw(host)
    if not mapping["success"]:
        result["error"] = mapping["error"]
        return result

    headers = mapping["headers"]
    try:
        admin_ip_idx = headers.index("ADMIN_IP")
        bmc_ip_idx = headers.index("BMC_IP")
        hostname_idx = headers.index("HOSTNAME")
        ib_ip_idx = headers.index("IB_IP") if "IB_IP" in headers else -1
    except ValueError as e:
        result["error"] = f"Required column not found: {e}"
        return result

    admin_octets = admin_subnet.split(".")
    ib_octets = ib_subnet.split(".") if ib_subnet else []

    for row in mapping["rows"]:
        if len(row) <= max(admin_ip_idx, bmc_ip_idx, hostname_idx):
            continue

        admin_ip = row[admin_ip_idx]
        bmc_ip = row[bmc_ip_idx]
        hostname = row[hostname_idx]
        ib_ip = row[ib_ip_idx] if ib_ip_idx >= 0 and len(row) > ib_ip_idx else ""

        if not admin_ip or not bmc_ip:
            continue

        bmc_parts = bmc_ip.split(".")
        admin_parts = admin_ip.split(".")

        if len(bmc_parts) != 4 or len(admin_parts) != 4:
            result["invalid_rows"].append({
                "hostname": hostname,
                "admin_ip": admin_ip,
                "bmc_ip": bmc_ip,
                "reason": "Invalid IP format",
            })
            continue

        # Expected ADMIN_IP: admin_subnet[0:2] + bmc_ip[2:4]
        expected_admin = f"{admin_octets[0]}.{admin_octets[1]}.{bmc_parts[2]}.{bmc_parts[3]}"

        if admin_ip != expected_admin:
            result["invalid_rows"].append({
                "hostname": hostname,
                "admin_ip": admin_ip,
                "bmc_ip": bmc_ip,
                "expected_admin_ip": expected_admin,
                "reason": f"ADMIN_IP mismatch: expected {expected_admin}",
            })
            continue

        # Check IB_IP if present and ib_subnet configured
        if ib_ip and ib_octets and len(ib_octets) == 4:
            ib_parts = ib_ip.split(".")
            expected_ib = f"{ib_octets[0]}.{ib_octets[1]}.{bmc_parts[2]}.{bmc_parts[3]}"
            if ib_ip != expected_ib:
                result["invalid_rows"].append({
                    "hostname": hostname,
                    "ib_ip": ib_ip,
                    "bmc_ip": bmc_ip,
                    "expected_ib_ip": expected_ib,
                    "reason": f"IB_IP mismatch: expected {expected_ib}",
                })
                continue

        result["valid_count"] += 1

    if result["invalid_rows"]:
        result["details"] = f"{len(result['invalid_rows'])} rows have IP correlation issues"
        result["error"] = result["details"]
    else:
        result["success"] = True
        result["details"] = f"All {result['valid_count']} rows have valid IP correlation"

    return result


def verify_parent_service_tag(host) -> Dict[str, Any]:
    """
    Verify PARENT_SERVICE_TAG rules in PXE mapping.

    Rules:
    1. Only slurm_node groups should have PARENT_SERVICE_TAG populated
    2. PARENT_SERVICE_TAG should reference a service_kube_node's SERVICE_TAG
    3. Other functional groups should have empty PARENT_SERVICE_TAG

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, valid_count, invalid_rows, details, error
    """
    result = {
        "success": False,
        "valid_count": 0,
        "invalid_rows": [],
        "details": "",
        "error": "",
    }

    mapping = read_bmc_pxe_mapping_raw(host)
    if not mapping["success"]:
        result["error"] = mapping["error"]
        return result

    headers = mapping["headers"]
    try:
        fg_idx = headers.index("FUNCTIONAL_GROUP_NAME")
        st_idx = headers.index("SERVICE_TAG")
        pst_idx = headers.index("PARENT_SERVICE_TAG")
        hostname_idx = headers.index("HOSTNAME")
    except ValueError as e:
        result["error"] = f"Required column not found: {e}"
        return result

    # Build set of valid parent service tags (from service_kube_node)
    valid_parent_tags = set()
    for row in mapping["rows"]:
        if len(row) <= max(fg_idx, st_idx):
            continue
        fg = row[fg_idx]
        if fg in VALID_PARENT_FUNCTIONAL_GROUPS:
            valid_parent_tags.add(row[st_idx])

    for row in mapping["rows"]:
        if len(row) <= max(fg_idx, st_idx, pst_idx, hostname_idx):
            continue

        fg = row[fg_idx]
        service_tag = row[st_idx]
        parent_tag = row[pst_idx]
        hostname = row[hostname_idx]

        requires_parent = fg in GROUPS_REQUIRING_PARENT_SERVICE_TAG

        if requires_parent:
            if not parent_tag:
                result["invalid_rows"].append({
                    "hostname": hostname,
                    "functional_group": fg,
                    "service_tag": service_tag,
                    "parent_service_tag": parent_tag,
                    "reason": "slurm_node missing PARENT_SERVICE_TAG",
                })
            elif parent_tag not in valid_parent_tags:
                result["invalid_rows"].append({
                    "hostname": hostname,
                    "functional_group": fg,
                    "service_tag": service_tag,
                    "parent_service_tag": parent_tag,
                    "reason": f"PARENT_SERVICE_TAG '{parent_tag}' not found in service_kube_node",
                })
            else:
                result["valid_count"] += 1
        else:
            if parent_tag:
                result["invalid_rows"].append({
                    "hostname": hostname,
                    "functional_group": fg,
                    "service_tag": service_tag,
                    "parent_service_tag": parent_tag,
                    "reason": f"{fg} should not have PARENT_SERVICE_TAG",
                })
            else:
                result["valid_count"] += 1

    if result["invalid_rows"]:
        result["details"] = f"{len(result['invalid_rows'])} rows have PARENT_SERVICE_TAG issues"
        result["error"] = result["details"]
    else:
        result["success"] = True
        result["details"] = f"All {result['valid_count']} rows have valid PARENT_SERVICE_TAG"

    return result


def get_pxe_mapping_bmc_ips_by_group(host, functional_group: str) -> Dict[str, Any]:
    """
    Get BMC IPs for a specific functional group from PXE mapping.

    Args:
        host: Testinfra host object
        functional_group: Functional group name

    Returns:
        Dict with success, ips, error
    """
    result = {
        "success": False,
        "ips": [],
        "error": "",
    }

    mapping = read_bmc_pxe_mapping_raw(host)
    if not mapping["success"]:
        result["error"] = mapping["error"]
        return result

    headers = mapping["headers"]
    try:
        fg_idx = headers.index("FUNCTIONAL_GROUP_NAME")
        bmc_ip_idx = headers.index("BMC_IP")
    except ValueError as e:
        result["error"] = f"Required column not found: {e}"
        return result

    for row in mapping["rows"]:
        if len(row) > max(fg_idx, bmc_ip_idx):
            if row[fg_idx] == functional_group and row[bmc_ip_idx]:
                result["ips"].append(row[bmc_ip_idx])

    result["ips"] = sorted(result["ips"])
    result["success"] = True
    return result
