# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Build Image module - Functions, messages, and variables for build_image automation.

This module automates the build_image_x86_64 playbook execution and validates:
- S3 containers are running (precheck)
- functional_group.yml is autogenerated correctly
- Base and compute images are available in regctl registry
- Images are pushed to S3 bucket

Usage:
    from automation_library.build_image.functions import (
        check_s3_containers,
        check_functional_group_file,
        check_registry_images,
        check_s3_bucket_images,
    )
    from automation_library.build_image.messages import TEST_NAMES
    from automation_library.build_image.vars import BUILD_IMAGE_VARS, S3_CONTAINERS
"""
