# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# =============================================================================
# VALIDATE SOFTWARE CONFIG FILE
# =============================================================================

- name: Load software_config.json as user_config
  ansible.builtin.set_fact:
    user_config: "{{ lookup('file', software_config_file) | from_json }}"
  register: software_config_load
  failed_when: false

- name: Fail if software_config.json has syntax errors
  ansible.builtin.fail:
    msg: "{{ software_config_syntax_fail_msg }}"
  when: software_config_load is failed

- name: Generate software JSON file names
  ansible.builtin.set_fact:
    software_names: "{{ user_config.softwares | default([]) | map(attribute='name') | list }}"
  when: user_config.softwares is defined

- name: Set empty software names if not defined
  ansible.builtin.set_fact:
    software_names: []
  when: user_config.softwares is not defined
