# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# =============================================================================
# CREDENTIAL VALIDATION TASKS
# =============================================================================
# Validates that credential files exist and are accessible.
# =============================================================================

- name: Initialize list of tags
  ansible.builtin.set_fact:
    omnia_run_tags: "{{ ansible_run_tags | default([]) | list }}"
  when: omnia_run_tags is not defined

- name: Validate credential files
  ansible.builtin.include_tasks: validate_credential_file.yml
  loop: "{{ credential_files }}"
  loop_control:
    loop_var: cred_config
  when: cred_config.condition | default(true) | bool

- name: Load and validate software config
  ansible.builtin.include_tasks: validate_software_config.yml
