# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Prepare OIM - Multi-Subnet Functions.

Functions for verifying multi-subnet (multi-RAC) CoreDHCP configuration
after prepare_oim execution. Handles detection, transformation verification,
and subnet entry validation in coredhcp.yaml.
"""

import ipaddress
from typing import Dict, Any, List

from automation_library.core import (
    load_input_file,
    get_functional_groups_from_pxe_mapping,
    get_nodes_info,
    NETWORK_SPEC_FILE,
)
from ..vars.multi_subnet_vars import (
    COREDHCP_CONFIG_PATH,
    CORESMD_COREDHCP_CONTAINER_FILE,
    CORESMD_COREDNS_CONTAINER_FILE,
    CORESMD_MULTISUBNET_IMAGE,
    MULTISUBNET_CORESMD_MARKER,
    MULTISUBNET_BOOTLOOP_MARKER,
    SINGLE_SUBNET_CORESMD_COMMENT,
    OPENCHAMI_TARGET,
)


# =============================================================================
# NETWORK SPEC HELPERS
# =============================================================================

def get_additional_subnets(host) -> List[Dict[str, str]]:
    """
    Get the additional_subnets list from network_spec.yml.

    Reads the Networks[0].admin_network.additional_subnets field.

    Args:
        host: Testinfra host object

    Returns:
        List of subnet dicts with keys: subnet, netmask_bits, router, dynamic_range.
        Returns empty list if not configured.
    """
    config = load_input_file(host, NETWORK_SPEC_FILE)
    networks = config.get("Networks", config.get("networks", []))
    for network in networks:
        if isinstance(network, dict):
            admin = network.get("admin_network", {})
            if admin:
                subnets = admin.get("additional_subnets", [])
                if subnets and isinstance(subnets, list):
                    return subnets
    return []


def has_additional_subnets(host) -> bool:
    """
    Check if additional_subnets are configured in network_spec.yml.

    Args:
        host: Testinfra host object

    Returns:
        True if additional_subnets list is non-empty
    """
    return len(get_additional_subnets(host)) > 0


# =============================================================================
# COREDHCP VERIFICATION FUNCTIONS
# =============================================================================

def check_coredhcp_file_exists(host) -> Dict[str, Any]:
    """
    Check if /etc/openchami/configs/coredhcp.yaml exists on the OIM host.

    This file is generated by prepare_oim.yml on the OIM host (outside container).

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, path, content (if exists), error
    """
    cmd = host.run(f"cat {COREDHCP_CONFIG_PATH} 2>/dev/null")
    if cmd.rc == 0 and cmd.stdout.strip():
        return {
            "success": True,
            "path": COREDHCP_CONFIG_PATH,
            "content": cmd.stdout,
            "error": "",
        }

    return {
        "success": False,
        "path": COREDHCP_CONFIG_PATH,
        "content": "",
        "error": f"File not found or empty: {COREDHCP_CONFIG_PATH}",
    }


def check_coredhcp_multisubnet_mode(host) -> Dict[str, Any]:
    """
    Check whether coredhcp.yaml is in multi-subnet mode.

    Detects three possible states:
    - 'multi-subnet': key=value coresmd format is active (uncommented).
      This means coresmd v0.6.0+ was available when prepare_oim ran.
    - 'commented': multi-subnet entries exist but are commented out.
      This means prepare_oim detected additional_subnets but coresmd
      was < v0.6.0 at template render time. The 6-step manual
      activation instructions are present in the file.
    - 'single-subnet': positional coresmd format only, no multi-subnet
      entries at all (neither active nor commented).

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, mode, details, error
    """
    file_result = check_coredhcp_file_exists(host)
    if not file_result["success"]:
        return {
            "success": False,
            "mode": "unknown",
            "details": "",
            "error": file_result["error"],
        }

    content = file_result["content"]

    # Scan for active and commented multi-subnet markers
    active_coresmd = False
    active_bootloop = False
    commented_coresmd = False
    commented_bootloop = False

    for line in content.split("\n"):
        stripped = line.strip()
        if stripped.startswith("#"):
            uncommented = stripped.lstrip("# ")
            if MULTISUBNET_CORESMD_MARKER in uncommented:
                commented_coresmd = True
            if MULTISUBNET_BOOTLOOP_MARKER in uncommented:
                commented_bootloop = True
        else:
            if MULTISUBNET_CORESMD_MARKER in stripped:
                active_coresmd = True
            if MULTISUBNET_BOOTLOOP_MARKER in stripped:
                active_bootloop = True

    # State 1: Active multi-subnet mode
    if active_coresmd and active_bootloop:
        return {
            "success": True,
            "mode": "multi-subnet",
            "details": (
                "coresmd plugin uses key=value format (svc_base_uri=...)\n"
                "bootloop plugin uses subnet_pool= directives"
            ),
            "error": "",
        }

    # State 2: Multi-subnet entries present but commented out
    if commented_coresmd and commented_bootloop:
        return {
            "success": True,
            "mode": "commented",
            "details": (
                "Multi-subnet entries are present in coredhcp.yaml "
                "but commented out (6-step manual activation required).\n"
                "This is expected when coresmd was < v0.6.0 at "
                "prepare_oim time but additional_subnets are configured."
            ),
            "error": "",
        }

    # Partial state (only one of the two markers found)
    if active_coresmd or active_bootloop:
        return {
            "success": False,
            "mode": "partial",
            "details": (
                f"Partial multi-subnet config detected. "
                f"coresmd key=value: {active_coresmd}, "
                f"bootloop subnet_pool: {active_bootloop}"
            ),
            "error": "Incomplete multi-subnet transformation",
        }

    return {
        "success": False,
        "mode": "single-subnet",
        "details": "coresmd uses positional argument format (single-subnet)",
        "error": "CoreDHCP is in single-subnet mode",
    }


def verify_subnet_entries_in_coredhcp(host) -> Dict[str, Any]:
    """
    Verify that all additional_subnets from network_spec.yml have corresponding
    entries in coredhcp.yaml.

    For each additional subnet, checks:
    - coresmd rule with subnet:CIDR,type:Node,routers:ROUTER
    - coresmd rule with subnet:CIDR,type:NodeBMC,routers:ROUTER
    - bootloop subnet_pool with CIDR,start_ip,end_ip

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, subnets (list of per-subnet results),
        missing_count, total, error
    """
    additional = get_additional_subnets(host)
    if not additional:
        return {
            "success": True,
            "subnets": [],
            "missing_count": 0,
            "total": 0,
            "error": "",
        }

    file_result = check_coredhcp_file_exists(host)
    if not file_result["success"]:
        return {
            "success": False,
            "subnets": [],
            "missing_count": len(additional),
            "total": len(additional),
            "error": file_result["error"],
        }

    content = file_result["content"]

    # Build both active and full (including commented) content for matching
    active_lines = []
    all_lines = []
    for line in content.split("\n"):
        stripped = line.strip()
        all_lines.append(stripped)
        if not stripped.startswith("#"):
            active_lines.append(stripped)
        else:
            # Strip comment prefix for matching commented entries
            all_lines.append(stripped.lstrip("# "))

    active_content = "\n".join(active_lines)
    all_content = "\n".join(all_lines)

    subnet_results = []
    missing_count = 0

    for subnet_cfg in additional:
        subnet = subnet_cfg.get("subnet", "")
        netmask = subnet_cfg.get("netmask_bits", "")
        router = subnet_cfg.get("router", "")
        dynamic_range = subnet_cfg.get("dynamic_range", "")
        cidr = f"{subnet}/{netmask}"

        # Expected entries
        node_rule = f"subnet:{cidr},type:Node,routers:{router},cidr:{netmask}"
        bmc_rule = f"subnet:{cidr},type:NodeBMC,routers:{router},cidr:{netmask}"

        # Parse dynamic range for bootloop
        range_parts = dynamic_range.split("-") if dynamic_range else []
        if len(range_parts) == 2:
            pool_entry = f"subnet_pool={cidr},{range_parts[0]},{range_parts[1]}"
        else:
            pool_entry = f"subnet_pool={cidr}"

        # Check active lines first, then fall back to all lines (commented)
        node_active = node_rule in active_content
        bmc_active = bmc_rule in active_content
        pool_active = pool_entry in active_content

        node_commented = node_rule in all_content
        bmc_commented = bmc_rule in all_content
        pool_commented = pool_entry in all_content

        # "found" = present in either active or commented form
        has_node_rule = node_active or node_commented
        has_bmc_rule = bmc_active or bmc_commented
        has_pool = pool_active or pool_commented

        all_found = has_node_rule and has_bmc_rule and has_pool
        if not all_found:
            missing_count += 1

        # Determine state per entry
        if node_active and bmc_active and pool_active:
            entry_state = "active"
        elif all_found:
            entry_state = "commented"
        else:
            entry_state = "missing"

        subnet_results.append({
            "subnet": cidr,
            "router": router,
            "dynamic_range": dynamic_range,
            "success": all_found,
            "state": entry_state,
            "node_rule_found": has_node_rule,
            "node_rule_active": node_active,
            "bmc_rule_found": has_bmc_rule,
            "bmc_rule_active": bmc_active,
            "pool_found": has_pool,
            "pool_active": pool_active,
            "expected_node_rule": f"rule={node_rule}",
            "expected_bmc_rule": f"rule={bmc_rule}",
            "expected_pool": pool_entry,
        })

    return {
        "success": missing_count == 0,
        "subnets": subnet_results,
        "missing_count": missing_count,
        "total": len(additional),
        "error": (
            f"{missing_count}/{len(additional)} subnet entries missing"
            if missing_count > 0 else ""
        ),
    }


# =============================================================================
# COREDHCP MULTI-SUBNET ACTIVATION (6-STEP PROCESS)
# =============================================================================

def activate_multisubnet_coredhcp(host) -> Dict[str, Any]:
    """
    Activate multi-subnet CoreDHCP configuration on the OIM host.

    Performs the 6-step process documented in coredhcp.yaml comments:
      1. Pull the coresmd v0.6.3 image (podman pull)
      2. Comment out the single-subnet coresmd and bootloop lines
      3. Uncomment the multi-subnet coresmd and bootloop blocks
      4. Update the coresmd image version in quadlet container files
      5. Reload systemd daemon (systemctl daemon-reload)
      6. Restart openchami.target (systemctl restart openchami.target)

    This function is idempotent — if multi-subnet mode is already active,
    it returns success without making changes.

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, steps (list of step results), error
    """
    steps = []

    # Pre-check: is multi-subnet already active?
    mode_result = check_coredhcp_multisubnet_mode(host)
    if mode_result.get("mode") == "multi-subnet":
        # Also verify quadlet images are at the correct version
        quadlet_ok = True
        for qf in (CORESMD_COREDHCP_CONTAINER_FILE,
                    CORESMD_COREDNS_CONTAINER_FILE):
            chk = host.run(
                f"grep -q 'Image={CORESMD_MULTISUBNET_IMAGE}' {qf}"
            )
            if chk.rc != 0:
                quadlet_ok = False
                break
        if quadlet_ok:
            return {
                "success": True,
                "steps": [{"step": 0, "name": "pre-check",
                            "detail": "Already in multi-subnet mode"}],
                "error": "",
            }
        # Multi-subnet config is active but quadlet images need updating
        # Skip to step 1 (pull) + step 4-6 only
        steps = [{"step": 0, "name": "pre-check", "success": True,
                  "detail": "Config is multi-subnet but quadlet images "
                            "need updating"}]
        skip_config_edit = True
    else:
        skip_config_edit = False

    # Verify coredhcp.yaml exists and has commented multi-subnet entries
    if not skip_config_edit:
        if mode_result.get("mode") not in ("commented", "single-subnet"):
            if not mode_result["success"]:
                return {
                    "success": False,
                    "steps": [],
                    "error": mode_result.get("error",
                                             "Cannot determine config mode"),
                }

    # ── Step 1: Pull coresmd image ──────────────────────────────────────
    pull_cmd = host.run(f"podman pull {CORESMD_MULTISUBNET_IMAGE}")
    step1_ok = pull_cmd.rc == 0
    steps.append({
        "step": 1,
        "name": "Pull coresmd image",
        "command": f"podman pull {CORESMD_MULTISUBNET_IMAGE}",
        "success": step1_ok,
        "detail": pull_cmd.stdout.strip() if step1_ok else pull_cmd.stderr.strip(),
    })
    if not step1_ok:
        return {
            "success": False,
            "steps": steps,
            "error": f"Step 1 failed: podman pull {CORESMD_MULTISUBNET_IMAGE}",
        }

    if not skip_config_edit:
        # ── Step 2: Comment out single-subnet coresmd and bootloop lines ─
        # Uses sed to find the two active lines after the single-subnet
        # comment and prepend them with '# '
        sed_comment = (
            f"sed -i '/{SINGLE_SUBNET_CORESMD_COMMENT.replace('/', '\\\\/')}/"
            "{n;s/^\\(    - coresmd:.*\\)/    # \\1/;n;"
            "s/^\\(    - bootloop:.*\\)/    # \\1/}' "
            f"{COREDHCP_CONFIG_PATH}"
        )
        comment_cmd = host.run(sed_comment)
        step2_ok = comment_cmd.rc == 0
        steps.append({
            "step": 2,
            "name": "Comment out single-subnet lines",
            "command": sed_comment,
            "success": step2_ok,
            "detail": "Single-subnet coresmd/bootloop lines commented out"
                      if step2_ok else comment_cmd.stderr.strip(),
        })
        if not step2_ok:
            return {
                "success": False,
                "steps": steps,
                "error": "Step 2 failed: could not comment out "
                         "single-subnet lines",
            }

        # ── Step 3: Uncomment multi-subnet coresmd and bootloop blocks ───
        # Remove the leading '# ' from all commented multi-subnet config
        # lines. Targets '    # - coresmd: |' through end of block,
        # and '    #     key=value' lines.
        sed_uncomment = (
            "sed -i '/^    # - coresmd: |/,/^$/{s/^    # /    /}' "
            f"{COREDHCP_CONFIG_PATH}"
        )
        uncomment_cmd = host.run(sed_uncomment)
        step3_ok = uncomment_cmd.rc == 0

        # Also uncomment bootloop block if it wasn't caught above
        sed_uncomment_bootloop = (
            "sed -i '/^    # - bootloop: |/,/^$/{s/^    # /    /}' "
            f"{COREDHCP_CONFIG_PATH}"
        )
        uncomment_boot_cmd = host.run(sed_uncomment_bootloop)
        step3_ok = step3_ok and uncomment_boot_cmd.rc == 0

        steps.append({
            "step": 3,
            "name": "Uncomment multi-subnet blocks",
            "command": sed_uncomment,
            "success": step3_ok,
            "detail": "Multi-subnet coresmd/bootloop blocks uncommented"
                      if step3_ok
                      else "Failed to uncomment multi-subnet blocks",
        })
        if not step3_ok:
            return {
                "success": False,
                "steps": steps,
                "error": "Step 3 failed: could not uncomment "
                         "multi-subnet blocks",
            }
    else:
        steps.append({
            "step": 2, "name": "Comment out single-subnet lines",
            "success": True, "detail": "Skipped (config already active)",
        })
        steps.append({
            "step": 3, "name": "Uncomment multi-subnet blocks",
            "success": True, "detail": "Skipped (config already active)",
        })

    # ── Step 4: Update coresmd image in quadlet container files ────────
    step4_ok = True
    step4_details = []
    for quadlet_file in (CORESMD_COREDHCP_CONTAINER_FILE,
                         CORESMD_COREDNS_CONTAINER_FILE):
        # Replace any coresmd image line with the target version
        sed_image = (
            f"sed -i 's|^Image=.*coresmd:.*|"
            f"Image={CORESMD_MULTISUBNET_IMAGE}|' {quadlet_file}"
        )
        img_cmd = host.run(sed_image)
        # Verify the image was actually updated
        verify_cmd = host.run(
            f"grep -q 'Image={CORESMD_MULTISUBNET_IMAGE}' {quadlet_file}"
        )
        if img_cmd.rc != 0 or verify_cmd.rc != 0:
            step4_ok = False
            actual = host.run(f"grep '^Image=' {quadlet_file}")
            step4_details.append(
                f"FAILED: {quadlet_file} "
                f"(current: {actual.stdout.strip()})"
            )
        else:
            step4_details.append(f"Updated: {quadlet_file}")

    steps.append({
        "step": 4,
        "name": "Update quadlet image references",
        "success": step4_ok,
        "detail": "; ".join(step4_details),
    })
    if not step4_ok:
        return {
            "success": False,
            "steps": steps,
            "error": "Step 4 failed: could not update quadlet container files",
        }

    # ── Step 5: Reload systemd daemon ──────────────────────────────────
    reload_cmd = host.run("systemctl daemon-reload")
    step5_ok = reload_cmd.rc == 0
    steps.append({
        "step": 5,
        "name": "Reload systemd daemon",
        "command": "systemctl daemon-reload",
        "success": step5_ok,
        "detail": "daemon-reload successful" if step5_ok
                  else reload_cmd.stderr.strip(),
    })
    if not step5_ok:
        return {
            "success": False,
            "steps": steps,
            "error": "Step 5 failed: systemctl daemon-reload",
        }

    # ── Step 6: Restart openchami.target ───────────────────────────────
    restart_cmd = host.run(f"systemctl restart {OPENCHAMI_TARGET}")
    step6_ok = restart_cmd.rc == 0
    steps.append({
        "step": 6,
        "name": "Restart openchami.target",
        "command": f"systemctl restart {OPENCHAMI_TARGET}",
        "success": step6_ok,
        "detail": "openchami.target restarted" if step6_ok
                  else restart_cmd.stderr.strip(),
    })

    return {
        "success": step6_ok,
        "steps": steps,
        "error": "" if step6_ok else "Step 6 failed: systemctl restart openchami.target",
    }


# =============================================================================
# NETWORK SPEC - PRIMARY ADMIN SUBNET HELPER
# =============================================================================

def _get_admin_network(host) -> Dict[str, str]:
    """
    Get primary admin_network config from network_spec.yml.

    Returns:
        Dict with subnet, netmask_bits, primary_oim_admin_ip keys.
        Empty dict on failure.
    """
    config = load_input_file(host, NETWORK_SPEC_FILE)
    networks = config.get("Networks", config.get("networks", []))
    for network in networks:
        if isinstance(network, dict):
            admin = network.get("admin_network", {})
            if admin:
                return admin
    return {}


# =============================================================================
# NODE-TO-SUBNET MAPPING VERIFICATION
# =============================================================================

def verify_node_subnet_mapping(host) -> Dict[str, Any]:
    """
    Verify that every node in PXE mapping has its ADMIN_IP within either the
    primary admin subnet or one of the additional_subnets.

    This is multi-subnet specific: it confirms that each provisioned node
    belongs to a known subnet that CoreDHCP is configured to serve.

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, total, matched, unmatched, subnet_map (per-subnet
        node list), node_results (per-node detail), error
    """
    # Build list of all known subnets (primary + additional)
    admin_net = _get_admin_network(host)
    if not admin_net:
        return {
            "success": False, "total": 0, "matched": 0, "unmatched": 0,
            "subnet_map": {}, "node_results": [],
            "error": "Could not read admin_network from network_spec.yml",
        }

    subnets = []
    primary_subnet = admin_net.get("subnet", "")
    primary_bits = admin_net.get("netmask_bits", "24")
    if primary_subnet:
        cidr = f"{primary_subnet}/{primary_bits}"
        subnets.append({
            "cidr": cidr,
            "network": ipaddress.ip_network(cidr, strict=False),
            "label": f"{cidr} (primary)",
        })

    for sub in get_additional_subnets(host):
        sub_addr = sub.get("subnet", "")
        sub_bits = sub.get("netmask_bits", "24")
        if sub_addr:
            cidr = f"{sub_addr}/{sub_bits}"
            subnets.append({
                "cidr": cidr,
                "network": ipaddress.ip_network(cidr, strict=False),
                "label": cidr,
            })

    if not subnets:
        return {
            "success": False, "total": 0, "matched": 0, "unmatched": 0,
            "subnet_map": {}, "node_results": [],
            "error": "No subnets found in network_spec.yml",
        }

    # Get all nodes from PXE mapping
    all_fg = get_functional_groups_from_pxe_mapping(host)
    all_nodes = []
    for fg in all_fg:
        nodes = get_nodes_info(host, search_by="functional_group",
                               search_value=fg)
        all_nodes.extend(nodes)

    if not all_nodes:
        return {
            "success": False, "total": 0, "matched": 0, "unmatched": 0,
            "subnet_map": {}, "node_results": [],
            "error": "No nodes found in PXE mapping",
        }

    # Classify each node into a subnet
    subnet_map = {s["label"]: [] for s in subnets}
    node_results = []
    unmatched = 0

    for node in all_nodes:
        admin_ip = node.get("admin_ip", "")
        hostname = node.get("hostname", "")
        fg = node.get("functional_group", "")

        if not admin_ip:
            node_results.append({
                "hostname": hostname, "functional_group": fg,
                "admin_ip": "", "subnet": None, "matched": False,
                "reason": "No ADMIN_IP",
            })
            unmatched += 1
            continue

        try:
            ip_obj = ipaddress.ip_address(admin_ip)
        except ValueError:
            node_results.append({
                "hostname": hostname, "functional_group": fg,
                "admin_ip": admin_ip, "subnet": None, "matched": False,
                "reason": f"Invalid IP: {admin_ip}",
            })
            unmatched += 1
            continue

        matched_subnet = None
        for sub in subnets:
            if ip_obj in sub["network"]:
                matched_subnet = sub["label"]
                subnet_map[matched_subnet].append(hostname)
                break

        if matched_subnet:
            node_results.append({
                "hostname": hostname, "functional_group": fg,
                "admin_ip": admin_ip, "subnet": matched_subnet,
                "matched": True, "reason": "",
            })
        else:
            node_results.append({
                "hostname": hostname, "functional_group": fg,
                "admin_ip": admin_ip, "subnet": None, "matched": False,
                "reason": f"{admin_ip} not in any configured subnet",
            })
            unmatched += 1

    return {
        "success": unmatched == 0,
        "total": len(all_nodes),
        "matched": len(all_nodes) - unmatched,
        "unmatched": unmatched,
        "subnet_map": subnet_map,
        "node_results": node_results,
        "error": (
            f"{unmatched} node(s) not in any configured subnet"
            if unmatched > 0 else ""
        ),
    }


# =============================================================================
# CROSS-SUBNET SSH REACHABILITY VERIFICATION
# =============================================================================

def verify_cross_subnet_ssh(host) -> Dict[str, Any]:
    """
    Verify SSH reachability from OIM to at least one node per additional subnet.

    Picks one representative node from each additional subnet (based on PXE
    mapping ADMIN_IP classification) and runs an SSH connectivity check from
    omnia_core container.

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, subnet_results (per-subnet detail), error
    """
    # First get the node-to-subnet mapping
    mapping = verify_node_subnet_mapping(host)
    if not mapping["success"] and not mapping.get("subnet_map"):
        return {
            "success": False,
            "subnet_results": [],
            "error": mapping.get("error", "Could not determine subnet mapping"),
        }

    additional = get_additional_subnets(host)
    if not additional:
        return {
            "success": True,
            "subnet_results": [],
            "error": "",
        }

    # Build set of additional subnet CIDRs
    additional_cidrs = set()
    for sub in additional:
        sub_addr = sub.get("subnet", "")
        sub_bits = sub.get("netmask_bits", "24")
        if sub_addr:
            additional_cidrs.add(f"{sub_addr}/{sub_bits}")

    # For each additional subnet, pick a representative node and SSH to it
    subnet_results = []
    all_ok = True

    for nr in mapping.get("node_results", []):
        if not nr.get("matched") or not nr.get("subnet"):
            continue

        # Check if this node's subnet is an additional subnet
        subnet_label = nr["subnet"]
        # subnet_label is either "cidr (primary)" or just "cidr"
        subnet_cidr = subnet_label.replace(" (primary)", "")
        if subnet_cidr not in additional_cidrs:
            continue

        # Check if we already tested this subnet
        already_tested = any(
            sr["subnet"] == subnet_label for sr in subnet_results
        )
        if already_tested:
            continue

        # SSH from omnia_core to this node
        admin_ip = nr["admin_ip"]
        hostname = nr["hostname"]
        ssh_cmd = (
            f"podman exec omnia_core "
            f"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 "
            f"root@{admin_ip} 'hostname'"
        )
        result = host.run(ssh_cmd)
        ssh_ok = result.rc == 0

        subnet_results.append({
            "subnet": subnet_label,
            "test_node": hostname,
            "test_ip": admin_ip,
            "ssh_success": ssh_ok,
            "output": result.stdout.strip() if ssh_ok
                      else result.stderr.strip(),
        })

        if not ssh_ok:
            all_ok = False

    # Log additional subnets that had no nodes (informational, not a failure)
    tested_cidrs = set()
    for sr in subnet_results:
        tested_cidrs.add(sr["subnet"].replace(" (primary)", ""))

    for cidr in additional_cidrs:
        if cidr not in tested_cidrs:
            subnet_results.append({
                "subnet": cidr,
                "test_node": None,
                "test_ip": None,
                "ssh_success": True,
                "output": "No nodes in PXE mapping — skipped",
            })

    return {
        "success": all_ok,
        "subnet_results": subnet_results,
        "error": "" if all_ok else "SSH failed for one or more subnets",
    }


# =============================================================================
# CORESMD RUNNING CONTAINER IMAGE VERIFICATION
# =============================================================================

def verify_coresmd_running_image(host) -> Dict[str, Any]:
    """
    Verify that the running coresmd-coredhcp and coresmd-coredns containers
    are using the expected multi-subnet image version.

    This goes beyond checking the quadlet file — it inspects the actual
    running container image to confirm the restart was effective.

    Args:
        host: Testinfra host object

    Returns:
        Dict with success, container_results (per-container detail), error
    """
    container_results = []
    all_ok = True

    for container_name in ("coresmd-coredhcp", "coresmd-coredns"):
        # Get the image of the running container
        inspect_cmd = host.run(
            f"podman inspect {container_name} "
            f"--format '{{{{.ImageName}}}}'"
        )

        if inspect_cmd.rc != 0:
            container_results.append({
                "container": container_name,
                "running": False,
                "actual_image": "",
                "expected_image": CORESMD_MULTISUBNET_IMAGE,
                "match": False,
                "error": f"Container not running or inspect failed: "
                         f"{inspect_cmd.stderr.strip()}",
            })
            all_ok = False
            continue

        actual_image = inspect_cmd.stdout.strip()
        match = actual_image == CORESMD_MULTISUBNET_IMAGE

        container_results.append({
            "container": container_name,
            "running": True,
            "actual_image": actual_image,
            "expected_image": CORESMD_MULTISUBNET_IMAGE,
            "match": match,
            "error": "" if match else (
                f"Expected {CORESMD_MULTISUBNET_IMAGE}, "
                f"got {actual_image}"
            ),
        })

        if not match:
            all_ok = False

    return {
        "success": all_ok,
        "container_results": container_results,
        "error": "" if all_ok else "One or more containers using wrong image",
    }
