# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Build Image - Messages and Test Variables.

This module contains all messages, status strings, error instructions,
and test variables for the build_image automation.

"""

from typing import Dict

from automation_library.build_image.vars.build_image_vars import (
    BUILD_IMAGE_VARS,
    S3_CONTAINERS,
)

# =============================================================================
# TEST VARIABLES (for pytest validation tests)
# =============================================================================

TEST_VARS = {
    "oim_server_ip": BUILD_IMAGE_VARS["oim_server_ip"],
    "ssh_alias": BUILD_IMAGE_VARS["ssh_alias"],
    "s3_containers": S3_CONTAINERS,
    "functional_group_file_path": BUILD_IMAGE_VARS["functional_group_file_path"],
    "s3_list_images_cmd": BUILD_IMAGE_VARS["s3_list_images_cmd"],
    "s3_bucket_name": BUILD_IMAGE_VARS["s3_bucket_name"],
    "image_types": BUILD_IMAGE_VARS["image_types"],
    "ssh_timeout": 5,
}

# Test names (displayed in test output header)
TEST_NAMES = {
    # Build stream job stage validation (first test)
    "build_stream_job_stage": (
        "Verify build_stream pipeline stage '{stage}' completed successfully"
    ),
    # Precheck
    "s3_containers_running": "Verify S3 containers are running (precheck)",
    "container_running": "Verify container {container} is running",
    # Functional group validation
    "functional_group_autogenerated": (
        "Validate functional_groups_config.yml is autogenerated correctly"
    ),
    "functional_group_content": (
        "Verify functional_groups_config.yml contains all roles and groups from pxe_mapping"
    ),
    # Registry validation
    "regctl_registry_images": "Validate base and compute images are available in regctl registry",
    # S3 bucket validation
    "s3_bucket_images": "Verify images are pushed to S3 bucket",
    "s3_bucket_functional_group_images": "Verify all 3 images for functional group {group}",
    # Image package verification (mounts and checks ALL images)
    "image_packages": "Verify packages installed in ALL S3 images (downloads, mounts, checks RPM db)",
}

# Test log messages
TEST_LOG_MSGS = {
    # Container messages
    "container_running": "Container {container} is running",
    "container_not_running": "Container {container} is NOT running",
    "s3_containers_ok": "All S3 containers are running",
    "s3_containers_failed": "{count} S3 container(s) not running",
    # Functional group messages
    "functional_group_file_exists": "functional_groups_config.yml exists at {path}",
    "functional_group_file_not_found": "functional_groups_config.yml not found at {path}",
    "functional_group_content_ok": (
        "functional_groups_config.yml contains all {count} functional groups from pxe_mapping"
    ),
    "functional_group_content_missing": (
        "functional_groups_config.yml missing {count} functional group(s)"
    ),
    "functional_group_groups_ok": (
        "functional_groups_config.yml contains all {count} groups from pxe_mapping"
    ),
    "functional_group_groups_missing": "functional_groups_config.yml missing {count} group(s)",
    # Registry messages
    "regctl_registry_images_ok": "All images available in regctl registry",
    "regctl_registry_images_missing": "{count} image(s) missing from regctl registry",
    # S3 bucket messages
    "s3_bucket_images_ok": "All images pushed to S3 bucket",
    "s3_bucket_images_missing": "{count} image(s) missing from S3 bucket",
    "s3_bucket_group_ok": "All 3 images for {group} found in S3 bucket",
    "s3_bucket_group_missing": "{count} image(s) missing for {group} in S3 bucket",
    # Image package verification messages
    "image_packages_ok": "All packages verified in all images",
    "image_packages_failed": "{count} image(s) have missing packages",
    # Build stream job validation messages
    "build_stream_disabled_skip": (
        "build_stream is DISABLED — skipping job stage validation"
    ),
    "build_stream_job_checking": (
        "Checking build_stream stage '{stage}' (source: {source})"
    ),
    "build_stream_job_ok": (
        "Stage '{stage}' COMPLETED — job UUID: {job_id} (source: {source})"
    ),
    "build_stream_job_failed": (
        "Stage '{stage}' is '{state}' — expected COMPLETED (job: {job_id})"
    ),
    "build_stream_job_not_found": (
        "No completed '{stage}' stage found in build_stream_db"
    ),
    # Prerequisite messages
    "squashfs_tools_not_installed": (
        "squashfs-tools package is NOT installed. "
        "This package is required to mount and verify S3 images."
    ),
    "squashfs_repo_not_configured": (
        "squashfs-tools is not available — no enabled repository provides it.\n"
        "Configure a repository that provides squashfs-tools and re-run."
    ),
}

# Test assert messages (user-friendly with instructions)
TEST_ASSERT_MSGS = {
    "container_not_running": """
╔══════════════════════════════════════════════════════════════════════════════╗
║ S3 CONTAINER CHECK FAILED: {container}
╠══════════════════════════════════════════════════════════════════════════════╣
║ Status: {status}
║
║ HOW TO FIX:
║   1. SSH to OIM server and check container: podman ps -a | grep {container}
║   2. Check container logs: podman logs {container}
║   3. Try restarting: podman restart {container}
║   4. If container doesn't exist, re-run prepare_oim.yml
╚══════════════════════════════════════════════════════════════════════════════╝
""",
    "s3_containers_failed": """
╔══════════════════════════════════════════════════════════════════════════════╗
║ S3 CONTAINERS PRECHECK FAILED
╠══════════════════════════════════════════════════════════════════════════════╣
║ {count} S3 container(s) not running
║
║ Failed containers:
{failed_list}
║
║ HOW TO FIX:
║   1. Check container status: podman ps -a | grep -E 'minio'
║   2. Check container logs: podman logs <container_name>
║   3. Restart containers: podman restart <container_name>
║   4. Re-run prepare_oim.yml if containers don't exist
╚══════════════════════════════════════════════════════════════════════════════╝
""",
    "functional_group_file_not_found": """
╔══════════════════════════════════════════════════════════════════════════════╗
║ FUNCTIONAL GROUP FILE NOT FOUND
╠══════════════════════════════════════════════════════════════════════════════╣
║ Expected: {path}
║ Status: {status}
║
║ HOW TO FIX:
║   1. Verify build_image playbook completed successfully
║   2. Check if omnia_core container is running: podman ps | grep omnia_core
║   3. Check path inside container: podman exec omnia_core ls -la /opt/omnia/.data/
║   4. Re-run build_image_x86_64.yml playbook
╚══════════════════════════════════════════════════════════════════════════════╝
""",
    "functional_group_content_missing": """
╔══════════════════════════════════════════════════════════════════════════════╗
║ FUNCTIONAL GROUP CONTENT VALIDATION FAILED
╠══════════════════════════════════════════════════════════════════════════════╣
║ Missing functional groups: {missing}
║
║ Expected from pxe_mapping file:
{expected_list}
║
║ HOW TO FIX:
║   1. Verify pxe_mapping file is correct
║   2. Check functional_groups_config.yml content: podman exec omnia_core cat /opt/omnia/.data/functional_groups_config.yml
║   3. Re-run build_image_x86_64.yml playbook
╚══════════════════════════════════════════════════════════════════════════════╝
""",
    "regctl_registry_images_missing": """
╔══════════════════════════════════════════════════════════════════════════════╗
║ REGCTL REGISTRY IMAGES VALIDATION FAILED
╠══════════════════════════════════════════════════════════════════════════════╣
║ Registry: {registry_url}
║ Missing images: {count}
║
║ Missing:
{missing_list}
║
║ HOW TO FIX:
║   1. Check regctl registry: regctl repo ls {registry_url}
║   2. Verify build_image playbook completed successfully
║   3. Check build logs in /opt/omnia/log/
║   4. Re-run build_image_x86_64.yml playbook
╚══════════════════════════════════════════════════════════════════════════════╝
""",
    "s3_bucket_images_missing": """
╔══════════════════════════════════════════════════════════════════════════════╗
║ S3 BUCKET IMAGES VALIDATION FAILED
╠══════════════════════════════════════════════════════════════════════════════╣
║ Missing images for functional group: {group}
║ Expected 3 images (initrd, rootfs, vmlinuz)
║
║ Missing:
{missing_list}
║
║ HOW TO FIX:
║   1. Check S3 bucket: s3cmd ls -Hr s3://boot-images
║   2. {storage_fix_hint}
║   3. Check build logs for errors
║   4. Re-run build_image playbook for the appropriate architecture
╚══════════════════════════════════════════════════════════════════════════════╝
""",
    "validation_failed": "Validation failed: {error}",
    "build_stream_job_stage_failed": """
\u2554{border}\u2557
\u2551 BUILD STREAM STAGE VALIDATION FAILED
\u2560{border}\u2563
\u2551 Stage   : {stage}
\u2551 Job ID  : {job_id}
\u2551 Status  : {state}
\u2551 Expected: COMPLETED
\u2551
\u2551 WHAT HAPPENED:
\u2551   The build_stream pipeline stage did not complete successfully.
\u2551   All downstream verifications (S3 images, registry) depend on this.
\u2551
\u2551 HOW TO FIX:
\u2551   1. Check build_stream API logs on the OIM server
\u2551   2. Query DB: podman exec omnia_postgres psql -U omnia -d build_stream_db
\u2551             -c "SELECT * FROM job_stages WHERE job_id = '{job_id}';"
\u2551   3. If stage is FAILED, re-trigger the build_stream pipeline
\u2551   4. If stage is still RUNNING, wait for it to complete
\u2551   5. To override: set build_stream_job_id in omnia_test_config.yml
\u255a{border}\u255d
""".format(border="═" * 74, stage="{stage}", job_id="{job_id}", state="{state}"),
}

# =============================================================================
# FUNCTION MESSAGES (for build_image_func.py)
# =============================================================================

BUILD_IMAGE_MSGS: Dict[str, str] = {

    # =========================================================================
    # PLAYBOOK EXECUTION
    # =========================================================================
    "playbook_start": "Starting build_image_x86_64.yml playbook execution...",
    "playbook_success": "build_image_x86_64.yml completed successfully",
    "playbook_fail": "build_image_x86_64.yml failed",
    "playbook_timeout": "build_image_x86_64.yml timed out after {timeout} seconds",

    # =========================================================================
    # PRECHECK - S3 CONTAINERS
    # =========================================================================
    "precheck_start": "Running prechecks for build_image...",
    "s3_check_start": "Checking S3 containers...",
    "s3_container_running": "S3 container {container} is running",
    "s3_container_not_running": "S3 container {container} is NOT running",
    "s3_containers_ok": "All S3 containers are running",
    "s3_containers_failed": "{failed} of {total} S3 containers not running",

    # =========================================================================
    # FUNCTIONAL GROUP VALIDATION
    # =========================================================================
    "functional_group_check_start": "Checking functional_groups_config.yml...",
    "functional_group_file_exists": "functional_groups_config.yml found at {path}",
    "functional_group_file_not_found": "functional_groups_config.yml NOT found at {path}",
    "functional_group_content_ok": (
        "functional_groups_config.yml contains all expected roles and groups"
    ),
    "functional_group_content_missing": "functional_groups_config.yml missing some roles/groups",

    # =========================================================================
    # REGISTRY VALIDATION
    # =========================================================================
    "registry_check_start": "Checking regctl registry for images...",
    "registry_images_ok": "All base and compute images available in registry",
    "registry_images_missing": "Some images missing from registry",

    # =========================================================================
    # S3 BUCKET VALIDATION
    # =========================================================================
    "s3_bucket_check_start": "Checking S3 bucket for images...",
    "s3_bucket_images_ok": "All images pushed to S3 bucket",
    "s3_bucket_images_missing": "Some images missing from S3 bucket",
    "s3_bucket_group_ok": "All 3 images for {group} found in S3 bucket",
    "s3_bucket_group_missing": "{missing} image(s) missing for {group}",

    # =========================================================================
    # VALIDATION SUMMARY
    # =========================================================================
    "validation_start": "Starting build_image validation...",
    "validation_pass": "All build_image validations PASSED",
    "validation_fail": "build_image validation FAILED: {failed_count} check(s) failed",
    "validation_summary": """
Validation Summary:
- Total: {total}
- Passed: {passed}
- Failed: {failed}
- Skipped: {skipped}
""",

    # =========================================================================
    # INSTRUCTIONS
    # =========================================================================
    "container_instruction": """
ACTION REQUIRED: S3 container is not running.
- Check container logs: podman logs {container}
- Check if container exists: podman ps -a | grep {container}
- Try restarting: podman restart {container}
""",

    "functional_group_instruction": """
ACTION REQUIRED: functional_groups_config.yml validation failed.
- Check file content: podman exec omnia_core cat /opt/omnia/.data/functional_groups_config.yml
- Verify pxe_mapping file is correct
- Re-run build_image_x86_64.yml playbook
""",

    "s3_bucket_instruction": """
ACTION REQUIRED: Images missing from S3 bucket.
- Check S3 bucket: s3cmd ls -Hr s3://boot-images
- Verify minio-server is running: podman ps | grep minio
- Check build logs for errors
- Re-run build_image_x86_64.yml playbook
""",
}
