# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""NFS-based implementation of InputDirectoryRepository."""

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_BUILD_STREAM_BASE = "/opt/omnia/build_stream"
DEFAULT_PLAYBOOK_INPUT_DIR = "/opt/omnia/input/project_build_stream"


class NfsInputDirectoryRepository:
    """NFS shared volume implementation for input directory management.

    Manages paths for input files generated by the GenerateInputFiles API
    and the destination directory expected by the playbook.
    """

    def __init__(
        self,
        build_stream_base: str = DEFAULT_BUILD_STREAM_BASE,
        playbook_input_dir: str = DEFAULT_PLAYBOOK_INPUT_DIR,
    ) -> None:
        """Initialize repository with base paths.

        Args:
            build_stream_base: Base path for build stream job data.
            playbook_input_dir: Destination path expected by the playbook.
        """
        self._build_stream_base = Path(build_stream_base)
        self._playbook_input_dir = Path(playbook_input_dir)

    def get_source_input_repository_path(self, job_id: str) -> Path:
        """Get source input directory path for a job.

        Args:
            job_id: Job identifier.

        Returns:
            Path like /opt/omnia/build_stream/{job_id}/input/
        """
        return self._build_stream_base / job_id / "input"

    def get_destination_input_repository_path(self) -> Path:
        """Get destination input directory path expected by playbook.

        Returns:
            Path like /opt/omnia/input/project_build_stream/
        """
        return self._playbook_input_dir

    def validate_input_directory(self, path: Path) -> bool:
        """Validate that input directory exists and contains required files.

        Args:
            path: Path to the input directory to validate.

        Returns:
            True if directory is valid and contains at least one file.
        """
        if not path.is_dir():
            logger.warning("Input directory does not exist: %s", path)
            return False

        has_files = any(path.iterdir())
        if not has_files:
            logger.warning("Input directory is empty: %s", path)
            return False

        return True
