#!/bin/bash
################################################################################################################
#  omnia_ofed:
#      Install OFED on all the cluster nodes using OFED ISO file provided
#
#################################################################################################################
echo "---------------------------"
echo "Checking for Mellanox cards"
mellanox_check=`lspci | grep -i Mellanox`
if [[ $mellanox_check == *"Mellanox"* ]]
then
  echo "Starting OFED installation"
  dnf groupinstall "Infiniband Support" -y
  dnf install infiniband-diags perftest qperf -y
  mlnxofed_ib_install -p /install/ofed/OFED_ISO -m --add-kernel-support --force -end-
  echo "exclude=dapl* ibacm infiniband* libmlx* librdma* opensm* ibutils* perftest* openmpi*" >> /etc/yum.conf
  echo "OFED installation completed"
else
  echo "Mellanox cards not found"
fi
echo "-----------------------------"