# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Display selected storage backend
  ansible.builtin.debug:
    msg: "OpenCHAMI image repository backend: {{ storage_backend | upper }}"

- name: Import packages task
  ansible.builtin.import_tasks: packages.yml

- name: Import configs task
  ansible.builtin.import_tasks: create_dirs.yml

- name: Import hosts task
  ansible.builtin.import_tasks: hosts.yml

- name: Import minio task (MinIO backend only)
  ansible.builtin.include_tasks: minio.yml
  when: storage_backend == 'minio'

- name: Import registry task
  ansible.builtin.import_tasks: registry.yml

- name: Import ochami task
  ansible.builtin.import_tasks: ochami.yml

- name: Import firewall task
  ansible.builtin.import_tasks: firewall.yml

- name: Import verify task
  ansible.builtin.import_tasks: verify.yml

- name: Import regctl tasks
  ansible.builtin.import_tasks: regctl.yml

- name: Import s3 bucket tasks
  ansible.builtin.import_tasks: s3_bucket.yml

- name: Import policy update tasks
  ansible.builtin.include_tasks: policy_update.yml
