# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Update package metadata
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Install Slurm build dependencies
  ansible.builtin.yum:
    name: "{{ slurm_dependencies.common_pkg + slurm_dependencies.tools_pkg + slurm_dependencies.slurm_pkg }}"
    state: present
  register: install_result

- name: Fail play if dependency installation failed
  ansible.builtin.fail:
    msg: "Slurm dependency installation failed on {{ inventory_hostname }}!"
  when: install_result is failed
