#!/bin/bash

#Usage: change_personality <k|s> <node_name>
#       k = Kubernetes
#       s = Slurm

new_personality=$1
dnsdomain=`dnsdomainname`
shift

if [ $new_personality == "k" ] 
then
# Change Personality to Kubernetes
  echo "[INFO] Changing personality to Kubernetes"
  for node in $*
  do
    echo -n "$node"
    scontrol update nodename=$node state=DRAIN reason="used for k8s"
    kubectl uncordon $node.$dnsdomain > /dev/null  
    echo " [OK]"
  done
elif [ $new_personality == "s" ]
then
# Change Personality to Slurm
  echo "INFO: Changing personality to Slurm"
  for node in $*
  do
    echo -n "$node"
    kubectl cordon $node.$dnsdomain > /dev/null
    scontrol update nodename=$node state=IDLE reason="used for Slurm"
    echo " [OK]"
  done
else
  echo "ERROR: $new_personality is not a valid personality. Use 'k' or 's'"
fi 
