# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install CRI-O package
  ansible.builtin.dnf:
    name: "cri-o-{{ k8s_target_version }}"
    state: present
    disablerepo: "*"
    enablerepo: "x86_64_rhel_{{ cluster_os_version }}_cri-o-v{{ k8s_target_version | regex_replace('\\.[0-9]+$', '') | replace('.', '-') }}"
  delegate_to: "{{ current_node_name }}"

- name: Reload systemd daemon after CRI-O install
  ansible.builtin.systemd:
    daemon_reload: true
  delegate_to: "{{ current_node_name }}"

- name: Restart CRI-O service after install
  ansible.builtin.systemd:
    name: crio
    state: restarted
  delegate_to: "{{ current_node_name }}"
