# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set empty image list
  ansible.builtin.set_fact:
    csi_powerscale_image_versions: []

- name: Fetch and store image versions
  ansible.builtin.set_fact:
    csi_powerscale_image_versions: "{{ csi_powerscale_image_versions + [item.package + ':' + item.tag] }}"
  loop: "{{ hostvars['localhost']['csi_driver_powerscale_packages_json']['csi_driver_powerscale']['cluster'] }}"
  when: item.type == 'image'

# Pulling images from pulp - always,partial, never
- name: Pull K8s services docker images from pulp
  ansible.builtin.command: nerdctl pull {{ item }}
  with_items: "{{ csi_powerscale_image_versions }}"
  changed_when: true
  failed_when: false
  when:
    - hostvars['localhost']['k8s_offline_install']

# Pulling images directly when k8s_offline_install: false, enable_routed_internet: true

- name: Pull K8s services docker images from proxy
  ansible.builtin.command: nerdctl pull {{ item }}
  with_items: "{{ csi_powerscale_image_versions }}"
  changed_when: true
  failed_when: false
  environment:
    http_proxy: "http://{{ hostvars['localhost']['admin_nic_ip'] }}:{{ proxy_port }}"
    https_proxy: "http://{{ hostvars['localhost']['admin_nic_ip'] }}:{{ proxy_port }}"
    no_proxy: "localhost,127.0.0.1,{{ hostvars['localhost']['admin_nic_ip'] }},{{ hostvars['localhost']['oim_hostname'] }}"   # noqa: yaml[line-length]
  when:
    - not hostvars['localhost']['k8s_offline_install']
    - hostvars['localhost']['enable_routed_internet']

# Pulling images directly when k8s_offline_install: false, enable_routed_internet: false

- name: Pull K8s services docker images from dedicated internet
  ansible.builtin.command: nerdctl pull {{ item }}
  with_items: "{{ csi_powerscale_image_versions }}"
  changed_when: true
  failed_when: false
  environment:
    no_proxy: "localhost,127.0.0.1,{{ hostvars['localhost']['admin_nic_ip'] }},{{ hostvars['localhost']['oim_hostname'] }}"   # noqa: yaml[line-length]
  when:
    - not hostvars['localhost']['k8s_offline_install']
    - not hostvars['localhost']['enable_routed_internet']

# Save pulled images as tar files (only kube_node_image_versions + image_versions)
- name: Save K8s service images to tar
  ansible.builtin.command: nerdctl save -o /root/k8s/{{ hostvars['localhost']['k8s_version'] }}/kube_node_configs/k8s-images/{{ item | regex_replace('[^a-zA-Z0-9_.-]', '_') }}.tar {{ item }} # noqa: yaml[line-length]
  with_items: "{{ csi_powerscale_image_versions }}"
  changed_when: true
  delegate_to: "{{ groups['kube_control_plane'][0] }}"

- name: Remove nameserver 10.233.0.3 from /etc/resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 10.233.0.3'
    state: absent
    backup: true

- name: Add nameservers after search line in /etc/resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver {{ item }}'
    insertafter: '^search'
    state: present
    backup: true
  loop: "{{ hostvars['localhost']['dns'] }}"


- name: Add nameserver 10.233.0.3 at the end
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 10.233.0.3'
    insertafter: EOF
    state: present
    backup: true
