"""
Wizard routes for Config Editor Module

Provides API endpoints for configuration generation and validation.
"""

import logging
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks, Request
from typing import Dict, Any, Optional
from pathlib import Path

from ....services.wizard_generator_service import WizardGeneratorService, GENERATED_CONFIG_FILENAMES
from ....services.job_store import JobStore, TooManyConcurrentJobsError
from ....api.v1.schemas.wizard_schemas import (
    DownloadFilesRequest
)
from ..dependencies import get_wizard_generator_service

logger = logging.getLogger(__name__)
router = APIRouter()


def run_catalog_generation(job_id: str, wizard_data: Dict[str, Any], 
                          output_dir: Optional[Path],
                          wizard_generator_service: WizardGeneratorService,
                          job_store: JobStore) -> None:
    """Run catalog generation in background.
    
    Args:
        job_id: Job identifier
        wizard_data: Wizard configuration data
        output_dir: Optional output directory Path
        wizard_generator_service: Wizard generator service instance
        job_store: Job store instance for tracking state
    """
    try:
        job_store.update_job(job_id, status="in_progress", progress=10)

        # Use existing backend functions to generate all configs
        job_store.update_job(job_id, progress=30)
        logger.info("Starting config generation for job %s", job_id)

        result = wizard_generator_service.generate_all_configs(
            job_id=job_id,
            update_job=job_store.update_job,
            wizard_data=wizard_data,
            output_dir=output_dir
        )

        logger.info("Config generation completed for job %s", job_id)
        job_store.update_job(job_id, progress=100, status="completed", result=result)

    except Exception as e:
        logger.exception("Config generation failed for job %s", job_id)
        job_store.update_job(job_id, status="failed", error=str(e), result={"error": str(e)})


# Endpoints
@router.post("/generate-all")
async def generate_all(
    wizard_data: Dict[str, Any],
    background_tasks: BackgroundTasks,
    request: Request,
    wizard_generator_service: WizardGeneratorService = Depends(get_wizard_generator_service)
) -> Dict[str, str]:
    """Trigger configuration generation.
    
    Args:
        wizard_data: Wizard configuration data
        background_tasks: FastAPI background tasks
        request: FastAPI request object
        wizard_generator_service: Wizard generator service instance
        
    Returns:
        Dictionary with job_id
    """
    job_store = request.app.state.job_store
    
    try:
        job_id = job_store.create_job()
    except TooManyConcurrentJobsError:
        raise HTTPException(429, "Too many generation jobs in progress. Please wait.")
    
    # Extract output_dir without mutating the request body
    output_dir = wizard_data.get("output_dir", None)
    output_path = Path(output_dir).expanduser().resolve() if output_dir else None
    
    generation_data = {k: v for k, v in wizard_data.items() if k != "output_dir"}
    
    background_tasks.add_task(
        run_catalog_generation,
        job_id,
        generation_data,
        output_path,
        wizard_generator_service,
        job_store
    )
    
    logger.info("Started config generation job %s", job_id)
    return {"job_id": job_id, "status": "pending"}


@router.get("/generate-all/{job_id}")
async def get_job_status(job_id: str, request: Request) -> Dict[str, Any]:
    """Get job status.

    Args:
        job_id: Job identifier
        request: FastAPI request object

    Returns:
        Job status dictionary
    """
    job_store = request.app.state.job_store
    job = job_store.get_job(job_id)
    if not job:
        raise HTTPException(404, "Job not found")
    logger.debug("Job status for %s: %s", job_id, job.get("status"))
    return job


@router.post("/download-files")
async def download_files(
    request: DownloadFilesRequest
):
    """Download generated configuration files as a ZIP archive.
    
    Args:
        request: DownloadFilesRequest containing input_dir path
        
    Returns:
        ZIP file containing all generated configuration files
    """
    from fastapi.responses import FileResponse
    from starlette.background import BackgroundTask
    import zipfile
    import tempfile
    import shutil
    from pathlib import Path
    import uuid
    
    input_dir = request.input_dir
    if not input_dir:
        raise HTTPException(400, "input_dir is required")
    
    input_path = Path(input_dir)
    if not input_path.exists():
        raise HTTPException(404, f"Input directory not found: {input_dir}")
    
    # Only include files that were generated by the wizard
    files_to_zip = [
        input_path / filename
        for filename in GENERATED_CONFIG_FILENAMES
        if (input_path / filename).is_file()
    ]
    if not files_to_zip:
        raise HTTPException(status_code=400, detail="No configuration files generated. Please generate files before downloading.")
    
    # Create a temporary directory for the ZIP file
    temp_dir = Path(tempfile.gettempdir()) / f"omnia-download-{uuid.uuid4()}"
    temp_dir.mkdir(exist_ok=True)
    zip_path = temp_dir / "omnia-config-files.zip"
    
    try:
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for file_path in files_to_zip:
                zipf.write(file_path, file_path.name)
        
        # Return the file with a background task to clean up
        def cleanup():
            try:
                shutil.rmtree(temp_dir, ignore_errors=True)
            except Exception as e:
                logger.warning("Failed to cleanup temp directory %s: %s", temp_dir, e)
        
        return FileResponse(
            zip_path,
            media_type="application/zip",
            filename="omnia-config-files.zip",
            background=BackgroundTask(cleanup)
        )
    except Exception as e:
        logger.exception("Failed to create ZIP file")
        # Clean up on error
        shutil.rmtree(temp_dir, ignore_errors=True)
        raise HTTPException(500, f"Failed to create ZIP file: {str(e)}")
