#!/bin/bash
################################################################################################################
#  omnia_bmc_config:
#      Configure bmc IP with /16 subnet in all the cluster nodes based on admin nic IP address.
#      Eg: If admin ip is 10.5.0.101 and bmc subnet is 10.3.0.0, bmc IP will be 10.3.0.101
#
#################################################################################################################
xcat_log=/var/log/xcat/xcat.log
echo "-----------------" >> $xcat_log
echo "Configure bmc nic" >> $xcat_log
#Fetch pxe ip
pxe_ip=`ifconfig | grep pxe_subnet_search_key | awk '{print $2}'`
echo "Fetching pxe nic ip address" >> $xcat_log

#Configure bmc ip
bmc_subnet=bmc_nic_subnet

IFS='.' read -ra bmc_array <<< "$bmc_subnet"
IFS='.' read -ra pxe_array <<< "$pxe_ip"
bmc_ip=${bmc_array[0]}'.'${bmc_array[1]}'.'${pxe_array[2]}'.'${pxe_array[3]}
echo "Fetching bmc ip address" >> $xcat_log
/opt/dell/srvadmin/sbin/racadm setniccfg -s $bmc_ip 255.255.0.0 0.0.0.0

echo "bmc nic configured" >> $xcat_log
echo "------------------" >> $xcat_log