#!/bin/bash
################################################################################################################
#  omnia_hostname:
#      Configure hostname in all the cluster nodes in the format nodename.domainname
#      Hostname should be in this format nodename.domainname to install centralized authentication tools like ipa
#
#################################################################################################################
echo "---------------------------"
echo "Configuring hostname"
HOSTNAMECTL=`which hostnamectl 2>&1 | grep -v "/usr/bin/which: no"`
if [ ! -z $HOSTNAMECTL ] && [ ! -z $NODE ]; then
    SET_HOSTNAME=$NODE
    if [ ! -z $DOMAIN ]; then
        SET_HOSTNAME=$NODE.$DOMAIN
    fi
    echo "Setting hostname to: $SET_HOSTNAME"
    hostnamectl set-hostname $SET_HOSTNAME
    echo $SET_HOSTNAME > /etc/hostname
    echo "Configured hostname"
fi
echo "-----------------------------"