---
name: Secret Leak Scan

'on':
  pull_request:
    branches:
      - main
      - staging
      - 'release_*'
      - 'issue-*'
      - 'pub/**'

jobs:
  gitleaks:
    name: Scan for secrets
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            harbor.dell.com/devsecops/devsecops-gitleaks@sha256:0f6c2ca3432fd1f06da468df03acb8821654736591c2fd862f55e75cacaf64f5 \
            detect \
            --source /repo \
            --config /repo/.github/workflows/.gitleaks.toml \
            --log-opts="origin/${{ github.base_ref }}..${{ github.sha }}" \
            --verbose \
            --no-git
