name: Gitleaks Scan
run-name: Gitleaks PR scan

on:
  push:
    branches:
      - main
      - staging
      - pub/build_stream
      - pub/telemetry
      - pub/q2_upgrade
      - gitleaks

  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    name: Scan for secrets
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_*_linux_x64.tar.gz
          tar -xzf gitleaks_*_linux_x64.tar.gz
          chmod +x gitleaks

      - name: Run Gitleaks scan
        run: |
          ./gitleaks detect --source . --log-opts="--all"
